apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-authkey
  namespace: clusters
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-backend
    kind: ClusterSecretStore
  target:
    name: tailscale-authkey
    creationPolicy: Owner
  data:
    - secretKey: auth-key
      remoteRef:
        key: hypershift/tailscale
        property: auth-key
